title: Stormchaser Roleplaying
description: The official website for Stormchaser Roleplaying.
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: Stormchaser-Roleplaying-Logo.png
aux_links:
  "Join us on Discord!":
    - "https://discord.gg/HX9EK4A"